services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
        MARIADB_ROOT_PASSWORD: password
        MARIADB_DATABASE: fragmir
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
